version: "3.9"
   
services:
 db:
  image: postgres
  volumes:
   - ./data/db:/var/lib/postgresql/data
  environment:
   - POSTGRES_DB=postgres
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  ports:
   - 5432:5432
 yauth:
  build: .
  ports:
   - 8080:8080
  depends_on:
   - db
  env_file:
   - server/.env
