export const LOGO_URL =
	'https://user-images.githubusercontent.com/6964334/147834043-fc384cab-e7ca-40f8-9663-38fc25fd5f3a.png';

export const TextInputType = {
	GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
	GITHUB_CLIENT_ID: 'GITHUB_CLIENT_ID',
	FACEBOOK_CLIENT_ID: 'FACEBOOK_CLIENT_ID',
	JWT_ROLE_CLAIM: 'JWT_ROLE_CLAIM',
	REDIS_URL: 'REDIS_URL',
	SMTP_HOST: 'SMTP_HOST',
	SMTP_PORT: 'SMTP_PORT',
	SMTP_USERNAME: 'SMTP_USERNAME',
	SENDER_EMAIL: 'SENDER_EMAIL',
	ORGANIZATION_NAME: 'ORGANIZATION_NAME',
	ORGANIZATION_LOGO: 'ORGANIZATION_LOGO',
};

export const HiddenInputType = {
	GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
	GITHUB_CLIENT_SECRET: 'GITHUB_CLIENT_SECRET',
	FACEBOOK_CLIENT_SECRET: 'FACEBOOK_CLIENT_SECRET',
	JWT_SECRET: 'JWT_SECRET',
	SMTP_PASSWORD: 'SMTP_PASSWORD',
	ADMIN_SECRET: 'ADMIN_SECRET',
};

export const ArrayInputType = {
	ROLES: 'ROLES',
	DEFAULT_ROLES: 'DEFAULT_ROLES',
	PROTECTED_ROLES: 'PROTECTED_ROLES',
	ALLOWED_ORIGINS: 'ALLOWED_ORIGINS',
};

export const SelectInputType = {
	JWT_TYPE: 'JWT_TYPE',
};

export const TextAreaInputType = {
	CUSTOM_ACCESS_TOKEN_SCRIPT: 'CUSTOM_ACCESS_TOKEN_SCRIPT',
};

export const ArrayInputOperations = {
	APPEND: 'APPEND',
	REMOVE: 'REMOVE',
};
