// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddEmailTemplateRequest struct {
	EventName string  `json:"event_name"`
	Subject   string  `json:"subject"`
	Template  string  `json:"template"`
	Design    *string `json:"design,omitempty"`
}

type AddOrgMemberRequest struct {
	OrgID  string   `json:"org_id"`
	UserID string   `json:"user_id"`
	Roles  []string `json:"roles,omitempty"`
}

type AddTrustedIssuerRequest struct {
	ServiceAccountID         string  `json:"service_account_id"`
	Name                     string  `json:"name"`
	IssuerURL                string  `json:"issuer_url"`
	KeySourceType            string  `json:"key_source_type"`
	JwksURL                  *string `json:"jwks_url,omitempty"`
	ExpectedAud              string  `json:"expected_aud"`
	SubjectClaim             *string `json:"subject_claim,omitempty"`
	AllowedSubjects          *string `json:"allowed_subjects,omitempty"`
	IssuerType               string  `json:"issuer_type"`
	SpiffeRefreshHintSeconds *int64  `json:"spiffe_refresh_hint_seconds,omitempty"`
	EnableTokenReview        *bool   `json:"enable_token_review,omitempty"`
	KubernetesAPIServerURL   *string `json:"kubernetes_api_server_url,omitempty"`
}

type AddVerifiedOrgDomainRequest struct {
	OrgID  string `json:"org_id"`
	Domain string `json:"domain"`
}

type AddWebhookRequest struct {
	EventName        string         `json:"event_name"`
	EventDescription *string        `json:"event_description,omitempty"`
	Endpoint         string         `json:"endpoint"`
	Enabled          bool           `json:"enabled"`
	Headers          map[string]any `json:"headers,omitempty"`
}

type AdminLoginRequest struct {
	AdminSecret string `json:"admin_secret"`
}

type AdminMeta struct {
	Roles                           []string `json:"roles"`
	DefaultRoles                    []string `json:"default_roles"`
	ProtectedRoles                  []string `json:"protected_roles"`
	IsMultiFactorAuthServiceEnabled bool     `json:"is_multi_factor_auth_service_enabled"`
}

type AdminSignupRequest struct {
	AdminSecret string `json:"admin_secret"`
}

type AuditLog struct {
	ID           string  `json:"id"`
	ActorID      *string `json:"actor_id,omitempty"`
	ActorType    *string `json:"actor_type,omitempty"`
	ActorEmail   *string `json:"actor_email,omitempty"`
	Action       *string `json:"action,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
	ResourceID   *string `json:"resource_id,omitempty"`
	IPAddress    *string `json:"ip_address,omitempty"`
	UserAgent    *string `json:"user_agent,omitempty"`
	Metadata     *string `json:"metadata,omitempty"`
	CreatedAt    *int64  `json:"created_at,omitempty"`
}

type AuditLogs struct {
	Pagination *Pagination `json:"pagination"`
	AuditLogs  []*AuditLog `json:"audit_logs"`
}

type AuthResponse struct {
	Message                    string    `json:"message"`
	ShouldShowEmailOtpScreen   *bool     `json:"should_show_email_otp_screen,omitempty"`
	ShouldShowMobileOtpScreen  *bool     `json:"should_show_mobile_otp_screen,omitempty"`
	ShouldShowTotpScreen       *bool     `json:"should_show_totp_screen,omitempty"`
	AccessToken                *string   `json:"access_token,omitempty"`
	IDToken                    *string   `json:"id_token,omitempty"`
	RefreshToken               *string   `json:"refresh_token,omitempty"`
	ExpiresIn                  *int64    `json:"expires_in,omitempty"`
	User                       *User     `json:"user,omitempty"`
	AuthenticatorScannerImage  *string   `json:"authenticator_scanner_image,omitempty"`
	AuthenticatorSecret        *string   `json:"authenticator_secret,omitempty"`
	AuthenticatorRecoveryCodes []*string `json:"authenticator_recovery_codes,omitempty"`
}

type CheckPermissionsInput struct {
	Checks []*PermissionCheckInput `json:"checks"`
	User   *string                 `json:"user,omitempty"`
}

type CheckPermissionsResponse struct {
	Results []*PermissionCheckResult `json:"results"`
}

type Client struct {
	ID            string   `json:"id"`
	ClientID      string   `json:"client_id"`
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	AllowedScopes []string `json:"allowed_scopes"`
	IsActive      bool     `json:"is_active"`
	CreatedAt     *int64   `json:"created_at,omitempty"`
	UpdatedAt     *int64   `json:"updated_at,omitempty"`
}

type ClientRequest struct {
	ID string `json:"id"`
}

type Clients struct {
	Pagination *Pagination `json:"pagination"`
	Clients    []*Client   `json:"clients"`
}

type CreateClientRequest struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	AllowedScopes []string `json:"allowed_scopes"`
}

type CreateClientResponse struct {
	Client       *Client `json:"client"`
	ClientSecret string  `json:"client_secret"`
}

type CreateOrgOIDCConnectionRequest struct {
	OrgID        string  `json:"org_id"`
	Name         string  `json:"name"`
	IssuerURL    string  `json:"issuer_url"`
	ClientID     string  `json:"client_id"`
	ClientSecret string  `json:"client_secret"`
	Scopes       *string `json:"scopes,omitempty"`
	RedirectURI  *string `json:"redirect_uri,omitempty"`
}

type CreateOrgSAMLConnectionRequest struct {
	OrgID             string  `json:"org_id"`
	Name              string  `json:"name"`
	IdpEntityID       string  `json:"idp_entity_id"`
	IdpSsoURL         string  `json:"idp_sso_url"`
	IdpCertificate    string  `json:"idp_certificate"`
	SpEntityID        *string `json:"sp_entity_id,omitempty"`
	AcsURL            *string `json:"acs_url,omitempty"`
	AttributeMapping  *string `json:"attribute_mapping,omitempty"`
	AllowIdpInitiated *bool   `json:"allow_idp_initiated,omitempty"`
}

type CreateOrganizationRequest struct {
	Name        string  `json:"name"`
	DisplayName *string `json:"display_name,omitempty"`
}

type CreateScimEndpointRequest struct {
	OrgID string `json:"org_id"`
}

type CreateScimEndpointResponse struct {
	ScimEndpoint *ScimEndpoint `json:"scim_endpoint"`
	Token        string        `json:"token"`
}

type DeleteEmailTemplateRequest struct {
	ID string `json:"id"`
}

type DeleteOrgDomainRequest struct {
	Domain string `json:"domain"`
}

type DeleteUserRequest struct {
	Email string `json:"email"`
}

type EmailTemplate struct {
	ID        string `json:"id"`
	EventName string `json:"event_name"`
	Template  string `json:"template"`
	Design    string `json:"design"`
	Subject   string `json:"subject"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

type EmailTemplates struct {
	Pagination     *Pagination      `json:"pagination"`
	EmailTemplates []*EmailTemplate `json:"email_templates"`
}

type Env struct {
	AccessTokenExpiryTime            *string  `json:"ACCESS_TOKEN_EXPIRY_TIME,omitempty"`
	AdminSecret                      *string  `json:"ADMIN_SECRET,omitempty"`
	DatabaseName                     *string  `json:"DATABASE_NAME,omitempty"`
	DatabaseURL                      *string  `json:"DATABASE_URL,omitempty"`
	DatabaseType                     *string  `json:"DATABASE_TYPE,omitempty"`
	DatabaseUsername                 *string  `json:"DATABASE_USERNAME,omitempty"`
	DatabasePassword                 *string  `json:"DATABASE_PASSWORD,omitempty"`
	DatabaseHost                     *string  `json:"DATABASE_HOST,omitempty"`
	DatabasePort                     *string  `json:"DATABASE_PORT,omitempty"`
	ClientID                         string   `json:"CLIENT_ID"`
	ClientSecret                     string   `json:"CLIENT_SECRET"`
	CustomAccessTokenScript          *string  `json:"CUSTOM_ACCESS_TOKEN_SCRIPT,omitempty"`
	SMTPHost                         *string  `json:"SMTP_HOST,omitempty"`
	SMTPPort                         *string  `json:"SMTP_PORT,omitempty"`
	SMTPUsername                     *string  `json:"SMTP_USERNAME,omitempty"`
	SMTPPassword                     *string  `json:"SMTP_PASSWORD,omitempty"`
	SMTPLocalName                    *string  `json:"SMTP_LOCAL_NAME,omitempty"`
	SenderEmail                      *string  `json:"SENDER_EMAIL,omitempty"`
	SenderName                       *string  `json:"SENDER_NAME,omitempty"`
	JwtType                          *string  `json:"JWT_TYPE,omitempty"`
	JwtSecret                        *string  `json:"JWT_SECRET,omitempty"`
	JwtPrivateKey                    *string  `json:"JWT_PRIVATE_KEY,omitempty"`
	JwtPublicKey                     *string  `json:"JWT_PUBLIC_KEY,omitempty"`
	AllowedOrigins                   []string `json:"ALLOWED_ORIGINS,omitempty"`
	AppURL                           *string  `json:"APP_URL,omitempty"`
	RedisURL                         *string  `json:"REDIS_URL,omitempty"`
	ResetPasswordURL                 *string  `json:"RESET_PASSWORD_URL,omitempty"`
	DisableEmailVerification         bool     `json:"DISABLE_EMAIL_VERIFICATION"`
	DisableBasicAuthentication       bool     `json:"DISABLE_BASIC_AUTHENTICATION"`
	DisableMobileBasicAuthentication bool     `json:"DISABLE_MOBILE_BASIC_AUTHENTICATION"`
	DisableMagicLinkLogin            bool     `json:"DISABLE_MAGIC_LINK_LOGIN"`
	DisableLoginPage                 bool     `json:"DISABLE_LOGIN_PAGE"`
	DisableSignUp                    bool     `json:"DISABLE_SIGN_UP"`
	DisableRedisForEnv               bool     `json:"DISABLE_REDIS_FOR_ENV"`
	DisableStrongPassword            bool     `json:"DISABLE_STRONG_PASSWORD"`
	DisableMultiFactorAuthentication bool     `json:"DISABLE_MULTI_FACTOR_AUTHENTICATION"`
	EnforceMultiFactorAuthentication bool     `json:"ENFORCE_MULTI_FACTOR_AUTHENTICATION"`
	Roles                            []string `json:"ROLES,omitempty"`
	ProtectedRoles                   []string `json:"PROTECTED_ROLES,omitempty"`
	DefaultRoles                     []string `json:"DEFAULT_ROLES,omitempty"`
	JwtRoleClaim                     *string  `json:"JWT_ROLE_CLAIM,omitempty"`
	GoogleClientID                   *string  `json:"GOOGLE_CLIENT_ID,omitempty"`
	GoogleClientSecret               *string  `json:"GOOGLE_CLIENT_SECRET,omitempty"`
	GithubClientID                   *string  `json:"GITHUB_CLIENT_ID,omitempty"`
	GithubClientSecret               *string  `json:"GITHUB_CLIENT_SECRET,omitempty"`
	FacebookClientID                 *string  `json:"FACEBOOK_CLIENT_ID,omitempty"`
	FacebookClientSecret             *string  `json:"FACEBOOK_CLIENT_SECRET,omitempty"`
	LinkedinClientID                 *string  `json:"LINKEDIN_CLIENT_ID,omitempty"`
	LinkedinClientSecret             *string  `json:"LINKEDIN_CLIENT_SECRET,omitempty"`
	AppleClientID                    *string  `json:"APPLE_CLIENT_ID,omitempty"`
	AppleClientSecret                *string  `json:"APPLE_CLIENT_SECRET,omitempty"`
	DiscordClientID                  *string  `json:"DISCORD_CLIENT_ID,omitempty"`
	DiscordClientSecret              *string  `json:"DISCORD_CLIENT_SECRET,omitempty"`
	TwitterClientID                  *string  `json:"TWITTER_CLIENT_ID,omitempty"`
	TwitterClientSecret              *string  `json:"TWITTER_CLIENT_SECRET,omitempty"`
	MicrosoftClientID                *string  `json:"MICROSOFT_CLIENT_ID,omitempty"`
	MicrosoftClientSecret            *string  `json:"MICROSOFT_CLIENT_SECRET,omitempty"`
	MicrosoftActiveDirectoryTenantID *string  `json:"MICROSOFT_ACTIVE_DIRECTORY_TENANT_ID,omitempty"`
	TwitchClientID                   *string  `json:"TWITCH_CLIENT_ID,omitempty"`
	TwitchClientSecret               *string  `json:"TWITCH_CLIENT_SECRET,omitempty"`
	RobloxClientID                   *string  `json:"ROBLOX_CLIENT_ID,omitempty"`
	RobloxClientSecret               *string  `json:"ROBLOX_CLIENT_SECRET,omitempty"`
	OrganizationName                 *string  `json:"ORGANIZATION_NAME,omitempty"`
	OrganizationLogo                 *string  `json:"ORGANIZATION_LOGO,omitempty"`
	AppCookieSecure                  bool     `json:"APP_COOKIE_SECURE"`
	AdminCookieSecure                bool     `json:"ADMIN_COOKIE_SECURE"`
	DefaultAuthorizeResponseType     *string  `json:"DEFAULT_AUTHORIZE_RESPONSE_TYPE,omitempty"`
	DefaultAuthorizeResponseMode     *string  `json:"DEFAULT_AUTHORIZE_RESPONSE_MODE,omitempty"`
	DisablePlayground                bool     `json:"DISABLE_PLAYGROUND"`
	DisableMailOtpLogin              bool     `json:"DISABLE_MAIL_OTP_LOGIN"`
	DisableTotpLogin                 bool     `json:"DISABLE_TOTP_LOGIN"`
}

type Error struct {
	Message string `json:"message"`
	Reason  string `json:"reason"`
}

type FgaExpandInput struct {
	Relation string `json:"relation"`
	Object   string `json:"object"`
}

type FgaExpandResponse struct {
	Tree string `json:"tree"`
}

type FgaListUsersInput struct {
	Object   string `json:"object"`
	Relation string `json:"relation"`
	UserType string `json:"user_type"`
}

type FgaListUsersResponse struct {
	Users []string `json:"users"`
}

type FgaModel struct {
	ID  string `json:"id"`
	Dsl string `json:"dsl"`
}

type FgaReadTuplesInput struct {
	User              *string `json:"user,omitempty"`
	Relation          *string `json:"relation,omitempty"`
	Object            *string `json:"object,omitempty"`
	PageSize          *int64  `json:"page_size,omitempty"`
	ContinuationToken *string `json:"continuation_token,omitempty"`
}

type FgaRelationInput struct {
	Relation string `json:"relation"`
	Object   string `json:"object"`
}

type FgaTuple struct {
	User     string `json:"user"`
	Relation string `json:"relation"`
	Object   string `json:"object"`
}

type FgaTupleInput struct {
	User     string `json:"user"`
	Relation string `json:"relation"`
	Object   string `json:"object"`
}

type FgaTuples struct {
	Tuples            []*FgaTuple `json:"tuples"`
	ContinuationToken *string     `json:"continuation_token,omitempty"`
}

type FgaWriteModelInput struct {
	Dsl string `json:"dsl"`
}

type FgaWriteTuplesInput struct {
	Tuples []*FgaTupleInput `json:"tuples"`
}

type ForgotPasswordRequest struct {
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	State       *string `json:"state,omitempty"`
	RedirectURI *string `json:"redirect_uri,omitempty"`
}

type ForgotPasswordResponse struct {
	Message                   string `json:"message"`
	ShouldShowMobileOtpScreen *bool  `json:"should_show_mobile_otp_screen,omitempty"`
}

type GenerateJWTKeysRequest struct {
	Type string `json:"type"`
}

type GenerateJWTKeysResponse struct {
	Secret     *string `json:"secret,omitempty"`
	PublicKey  *string `json:"public_key,omitempty"`
	PrivateKey *string `json:"private_key,omitempty"`
}

type GetUserRequest struct {
	ID    *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
}

type InviteMemberRequest struct {
	Emails      []string `json:"emails"`
	RedirectURI *string  `json:"redirect_uri,omitempty"`
}

type InviteMembersResponse struct {
	Message string  `json:"message"`
	Users   []*User `json:"Users"`
}

type ListAuditLogRequest struct {
	Pagination    *PaginationRequest `json:"pagination,omitempty"`
	Action        *string            `json:"action,omitempty"`
	ActorID       *string            `json:"actor_id,omitempty"`
	ResourceType  *string            `json:"resource_type,omitempty"`
	ResourceID    *string            `json:"resource_id,omitempty"`
	FromTimestamp *int64             `json:"from_timestamp,omitempty"`
	ToTimestamp   *int64             `json:"to_timestamp,omitempty"`
}

type ListClientsRequest struct {
	Pagination *PaginatedRequest `json:"pagination,omitempty"`
}

type ListOrgDomainsRequest struct {
	OrgID      string            `json:"org_id"`
	Pagination *PaginatedRequest `json:"pagination,omitempty"`
}

type ListOrgMembersRequest struct {
	OrgID      string            `json:"org_id"`
	Pagination *PaginatedRequest `json:"pagination,omitempty"`
}

type ListOrganizationsRequest struct {
	Pagination *PaginatedRequest `json:"pagination,omitempty"`
}

type ListPermissionsInput struct {
	Relation   *string `json:"relation,omitempty"`
	ObjectType *string `json:"object_type,omitempty"`
	User       *string `json:"user,omitempty"`
}

type ListPermissionsResponse struct {
	Objects     []string      `json:"objects"`
	Permissions []*Permission `json:"permissions"`
	Truncated   bool          `json:"truncated"`
}

type ListTrustedIssuersRequest struct {
	ServiceAccountID *string           `json:"service_account_id,omitempty"`
	Pagination       *PaginatedRequest `json:"pagination,omitempty"`
}

type ListUsersRequest struct {
	Pagination *PaginationRequest `json:"pagination,omitempty"`
	Query      *string            `json:"query,omitempty"`
}

type ListWebhookLogRequest struct {
	Pagination *PaginationRequest `json:"pagination,omitempty"`
	WebhookID  *string            `json:"webhook_id,omitempty"`
}

type LoginRequest struct {
	Email       *string  `json:"email,omitempty"`
	PhoneNumber *string  `json:"phone_number,omitempty"`
	Password    string   `json:"password"`
	Roles       []string `json:"roles,omitempty"`
	Scope       []string `json:"scope,omitempty"`
	State       *string  `json:"state,omitempty"`
}

type MagicLinkLoginRequest struct {
	Email       string   `json:"email"`
	Roles       []string `json:"roles,omitempty"`
	Scope       []string `json:"scope,omitempty"`
	State       *string  `json:"state,omitempty"`
	RedirectURI *string  `json:"redirect_uri,omitempty"`
}

type Meta struct {
	Version                            string `json:"version"`
	ClientID                           string `json:"client_id"`
	IsGoogleLoginEnabled               bool   `json:"is_google_login_enabled"`
	IsFacebookLoginEnabled             bool   `json:"is_facebook_login_enabled"`
	IsGithubLoginEnabled               bool   `json:"is_github_login_enabled"`
	IsLinkedinLoginEnabled             bool   `json:"is_linkedin_login_enabled"`
	IsAppleLoginEnabled                bool   `json:"is_apple_login_enabled"`
	IsDiscordLoginEnabled              bool   `json:"is_discord_login_enabled"`
	IsTwitterLoginEnabled              bool   `json:"is_twitter_login_enabled"`
	IsMicrosoftLoginEnabled            bool   `json:"is_microsoft_login_enabled"`
	IsTwitchLoginEnabled               bool   `json:"is_twitch_login_enabled"`
	IsRobloxLoginEnabled               bool   `json:"is_roblox_login_enabled"`
	IsEmailVerificationEnabled         bool   `json:"is_email_verification_enabled"`
	IsBasicAuthenticationEnabled       bool   `json:"is_basic_authentication_enabled"`
	IsMagicLinkLoginEnabled            bool   `json:"is_magic_link_login_enabled"`
	IsSignUpEnabled                    bool   `json:"is_sign_up_enabled"`
	IsStrongPasswordEnabled            bool   `json:"is_strong_password_enabled"`
	IsMultiFactorAuthEnabled           bool   `json:"is_multi_factor_auth_enabled"`
	IsMobileBasicAuthenticationEnabled bool   `json:"is_mobile_basic_authentication_enabled"`
	IsPhoneVerificationEnabled         bool   `json:"is_phone_verification_enabled"`
	IsOrgDiscoveryEnabled              bool   `json:"is_org_discovery_enabled"`
	IsTotpMfaEnabled                   bool   `json:"is_totp_mfa_enabled"`
	IsEmailOtpMfaEnabled               bool   `json:"is_email_otp_mfa_enabled"`
	IsSmsOtpMfaEnabled                 bool   `json:"is_sms_otp_mfa_enabled"`
	IsWebauthnEnabled                  bool   `json:"is_webauthn_enabled"`
}

type MobileLoginRequest struct {
	PhoneNumber string   `json:"phone_number"`
	Password    string   `json:"password"`
	Roles       []string `json:"roles,omitempty"`
	Scope       []string `json:"scope,omitempty"`
	State       *string  `json:"state,omitempty"`
}

type MobileSignUpRequest struct {
	Email                    *string        `json:"email,omitempty"`
	GivenName                *string        `json:"given_name,omitempty"`
	FamilyName               *string        `json:"family_name,omitempty"`
	MiddleName               *string        `json:"middle_name,omitempty"`
	Nickname                 *string        `json:"nickname,omitempty"`
	Gender                   *string        `json:"gender,omitempty"`
	Birthdate                *string        `json:"birthdate,omitempty"`
	PhoneNumber              string         `json:"phone_number"`
	Picture                  *string        `json:"picture,omitempty"`
	Password                 string         `json:"password"`
	ConfirmPassword          string         `json:"confirm_password"`
	Roles                    []string       `json:"roles,omitempty"`
	Scope                    []string       `json:"scope,omitempty"`
	RedirectURI              *string        `json:"redirect_uri,omitempty"`
	IsMultiFactorAuthEnabled *bool          `json:"is_multi_factor_auth_enabled,omitempty"`
	State                    *string        `json:"state,omitempty"`
	AppData                  map[string]any `json:"app_data,omitempty"`
}

type Mutation struct {
}

type OAuthRevokeRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type OrgDomain struct {
	Domain     string `json:"domain"`
	OrgID      string `json:"org_id"`
	VerifiedAt *int64 `json:"verified_at,omitempty"`
	CreatedAt  *int64 `json:"created_at,omitempty"`
	UpdatedAt  *int64 `json:"updated_at,omitempty"`
}

type OrgDomainChallenge struct {
	Domain      string `json:"domain"`
	RecordType  string `json:"record_type"`
	RecordName  string `json:"record_name"`
	RecordValue string `json:"record_value"`
}

type OrgDomains struct {
	Pagination *Pagination  `json:"pagination"`
	OrgDomains []*OrgDomain `json:"org_domains"`
}

type OrgMember struct {
	ID         string   `json:"id"`
	OrgID      string   `json:"org_id"`
	UserID     string   `json:"user_id"`
	Email      *string  `json:"email,omitempty"`
	GivenName  *string  `json:"given_name,omitempty"`
	FamilyName *string  `json:"family_name,omitempty"`
	Roles      []string `json:"roles"`
	CreatedAt  *int64   `json:"created_at,omitempty"`
	UpdatedAt  *int64   `json:"updated_at,omitempty"`
}

type OrgMembers struct {
	Pagination *Pagination  `json:"pagination"`
	OrgMembers []*OrgMember `json:"org_members"`
}

type OrgOIDCConnection struct {
	ID          string  `json:"id"`
	OrgID       string  `json:"org_id"`
	Name        string  `json:"name"`
	IssuerURL   string  `json:"issuer_url"`
	SsoClientID string  `json:"sso_client_id"`
	Scopes      *string `json:"scopes,omitempty"`
	RedirectURI *string `json:"redirect_uri,omitempty"`
	IsActive    bool    `json:"is_active"`
	CreatedAt   *int64  `json:"created_at,omitempty"`
	UpdatedAt   *int64  `json:"updated_at,omitempty"`
}

type OrgOIDCConnectionRequest struct {
	ID    *string `json:"id,omitempty"`
	OrgID *string `json:"org_id,omitempty"`
}

type OrgSAMLConnection struct {
	ID                string  `json:"id"`
	OrgID             string  `json:"org_id"`
	Name              string  `json:"name"`
	IdpEntityID       string  `json:"idp_entity_id"`
	IdpSsoURL         *string `json:"idp_sso_url,omitempty"`
	SpEntityID        *string `json:"sp_entity_id,omitempty"`
	AcsURL            *string `json:"acs_url,omitempty"`
	AttributeMapping  *string `json:"attribute_mapping,omitempty"`
	AllowIdpInitiated bool    `json:"allow_idp_initiated"`
	IsActive          bool    `json:"is_active"`
	CreatedAt         *int64  `json:"created_at,omitempty"`
	UpdatedAt         *int64  `json:"updated_at,omitempty"`
}

type OrgSAMLConnectionRequest struct {
	ID    *string `json:"id,omitempty"`
	OrgID *string `json:"org_id,omitempty"`
}

type Organization struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	DisplayName *string `json:"display_name,omitempty"`
	Enabled     bool    `json:"enabled"`
	CreatedAt   *int64  `json:"created_at,omitempty"`
	UpdatedAt   *int64  `json:"updated_at,omitempty"`
}

type OrganizationRequest struct {
	ID string `json:"id"`
}

type Organizations struct {
	Pagination    *Pagination     `json:"pagination"`
	Organizations []*Organization `json:"organizations"`
}

type PaginatedRequest struct {
	Pagination *PaginationRequest `json:"pagination,omitempty"`
}

type Pagination struct {
	Limit  int64 `json:"limit"`
	Page   int64 `json:"page"`
	Offset int64 `json:"offset"`
	Total  int64 `json:"total"`
}

type PaginationRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Page  *int64 `json:"page,omitempty"`
}

type Permission struct {
	Object   string `json:"object"`
	Relation string `json:"relation"`
}

type PermissionCheckInput struct {
	Relation         string           `json:"relation"`
	Object           string           `json:"object"`
	ContextualTuples []*FgaTupleInput `json:"contextual_tuples,omitempty"`
}

type PermissionCheckResult struct {
	Relation string `json:"relation"`
	Object   string `json:"object"`
	Allowed  bool   `json:"allowed"`
}

type Query struct {
}

type RemoveOrgMemberRequest struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

type RequestOrgDomainRequest struct {
	OrgID  string `json:"org_id"`
	Domain string `json:"domain"`
}

type ResendOTPRequest struct {
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	State       *string `json:"state,omitempty"`
}

type ResendVerifyEmailRequest struct {
	Email      string  `json:"email"`
	Identifier string  `json:"identifier"`
	State      *string `json:"state,omitempty"`
}

type ResetPasswordRequest struct {
	Token           *string `json:"token,omitempty"`
	Otp             *string `json:"otp,omitempty"`
	PhoneNumber     *string `json:"phone_number,omitempty"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirm_password"`
}

type Response struct {
	Message string `json:"message"`
}

type ScimEndpoint struct {
	ID        string `json:"id"`
	OrgID     string `json:"org_id"`
	Enabled   bool   `json:"enabled"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

type ScimEndpointRequest struct {
	OrgID string `json:"org_id"`
}

type SessionQueryRequest struct {
	Roles             []string            `json:"roles,omitempty"`
	Scope             []string            `json:"scope,omitempty"`
	State             *string             `json:"state,omitempty"`
	RequiredRelations []*FgaRelationInput `json:"required_relations,omitempty"`
}

type SignUpRequest struct {
	Email                    *string        `json:"email,omitempty"`
	GivenName                *string        `json:"given_name,omitempty"`
	FamilyName               *string        `json:"family_name,omitempty"`
	MiddleName               *string        `json:"middle_name,omitempty"`
	Nickname                 *string        `json:"nickname,omitempty"`
	Gender                   *string        `json:"gender,omitempty"`
	Birthdate                *string        `json:"birthdate,omitempty"`
	PhoneNumber              *string        `json:"phone_number,omitempty"`
	Picture                  *string        `json:"picture,omitempty"`
	Password                 string         `json:"password"`
	ConfirmPassword          string         `json:"confirm_password"`
	Roles                    []string       `json:"roles,omitempty"`
	Scope                    []string       `json:"scope,omitempty"`
	RedirectURI              *string        `json:"redirect_uri,omitempty"`
	IsMultiFactorAuthEnabled *bool          `json:"is_multi_factor_auth_enabled,omitempty"`
	State                    *string        `json:"state,omitempty"`
	AppData                  map[string]any `json:"app_data,omitempty"`
}

type TestEndpointRequest struct {
	Endpoint         string         `json:"endpoint"`
	EventName        string         `json:"event_name"`
	EventDescription *string        `json:"event_description,omitempty"`
	Headers          map[string]any `json:"headers,omitempty"`
}

type TestEndpointResponse struct {
	HTTPStatus *int64  `json:"http_status,omitempty"`
	Response   *string `json:"response,omitempty"`
}

type TrustedIssuer struct {
	ID                       string  `json:"id"`
	ServiceAccountID         string  `json:"service_account_id"`
	Name                     string  `json:"name"`
	IssuerURL                string  `json:"issuer_url"`
	KeySourceType            string  `json:"key_source_type"`
	JwksURL                  *string `json:"jwks_url,omitempty"`
	ExpectedAud              string  `json:"expected_aud"`
	SubjectClaim             string  `json:"subject_claim"`
	AllowedSubjects          *string `json:"allowed_subjects,omitempty"`
	IssuerType               string  `json:"issuer_type"`
	IsActive                 bool    `json:"is_active"`
	SpiffeRefreshHintSeconds *int64  `json:"spiffe_refresh_hint_seconds,omitempty"`
	EnableTokenReview        bool    `json:"enable_token_review"`
	KubernetesAPIServerURL   *string `json:"kubernetes_api_server_url,omitempty"`
	CreatedAt                *int64  `json:"created_at,omitempty"`
	UpdatedAt                *int64  `json:"updated_at,omitempty"`
}

type TrustedIssuerRequest struct {
	ID string `json:"id"`
}

type TrustedIssuers struct {
	Pagination     *Pagination      `json:"pagination"`
	TrustedIssuers []*TrustedIssuer `json:"trusted_issuers"`
}

type UpdateAccessRequest struct {
	UserID string `json:"user_id"`
}

type UpdateClientRequest struct {
	ID            string   `json:"id"`
	Name          *string  `json:"name,omitempty"`
	Description   *string  `json:"description,omitempty"`
	AllowedScopes []string `json:"allowed_scopes,omitempty"`
	IsActive      *bool    `json:"is_active,omitempty"`
}

type UpdateEmailTemplateRequest struct {
	ID        string  `json:"id"`
	EventName *string `json:"event_name,omitempty"`
	Template  *string `json:"template,omitempty"`
	Subject   *string `json:"subject,omitempty"`
	Design    *string `json:"design,omitempty"`
}

type UpdateEnvRequest struct {
	AccessTokenExpiryTime            *string  `json:"ACCESS_TOKEN_EXPIRY_TIME,omitempty"`
	AdminSecret                      *string  `json:"ADMIN_SECRET,omitempty"`
	CustomAccessTokenScript          *string  `json:"CUSTOM_ACCESS_TOKEN_SCRIPT,omitempty"`
	OldAdminSecret                   *string  `json:"OLD_ADMIN_SECRET,omitempty"`
	SMTPHost                         *string  `json:"SMTP_HOST,omitempty"`
	SMTPPort                         *string  `json:"SMTP_PORT,omitempty"`
	SMTPUsername                     *string  `json:"SMTP_USERNAME,omitempty"`
	SMTPPassword                     *string  `json:"SMTP_PASSWORD,omitempty"`
	SMTPLocalName                    *string  `json:"SMTP_LOCAL_NAME,omitempty"`
	SenderEmail                      *string  `json:"SENDER_EMAIL,omitempty"`
	SenderName                       *string  `json:"SENDER_NAME,omitempty"`
	JwtType                          *string  `json:"JWT_TYPE,omitempty"`
	JwtSecret                        *string  `json:"JWT_SECRET,omitempty"`
	JwtPrivateKey                    *string  `json:"JWT_PRIVATE_KEY,omitempty"`
	JwtPublicKey                     *string  `json:"JWT_PUBLIC_KEY,omitempty"`
	AllowedOrigins                   []string `json:"ALLOWED_ORIGINS,omitempty"`
	AppURL                           *string  `json:"APP_URL,omitempty"`
	ResetPasswordURL                 *string  `json:"RESET_PASSWORD_URL,omitempty"`
	AppCookieSecure                  *bool    `json:"APP_COOKIE_SECURE,omitempty"`
	AdminCookieSecure                *bool    `json:"ADMIN_COOKIE_SECURE,omitempty"`
	DisableEmailVerification         *bool    `json:"DISABLE_EMAIL_VERIFICATION,omitempty"`
	DisableBasicAuthentication       *bool    `json:"DISABLE_BASIC_AUTHENTICATION,omitempty"`
	DisableMobileBasicAuthentication *bool    `json:"DISABLE_MOBILE_BASIC_AUTHENTICATION,omitempty"`
	DisableMagicLinkLogin            *bool    `json:"DISABLE_MAGIC_LINK_LOGIN,omitempty"`
	DisableLoginPage                 *bool    `json:"DISABLE_LOGIN_PAGE,omitempty"`
	DisableSignUp                    *bool    `json:"DISABLE_SIGN_UP,omitempty"`
	DisableRedisForEnv               *bool    `json:"DISABLE_REDIS_FOR_ENV,omitempty"`
	DisableStrongPassword            *bool    `json:"DISABLE_STRONG_PASSWORD,omitempty"`
	DisableMultiFactorAuthentication *bool    `json:"DISABLE_MULTI_FACTOR_AUTHENTICATION,omitempty"`
	EnforceMultiFactorAuthentication *bool    `json:"ENFORCE_MULTI_FACTOR_AUTHENTICATION,omitempty"`
	Roles                            []string `json:"ROLES,omitempty"`
	ProtectedRoles                   []string `json:"PROTECTED_ROLES,omitempty"`
	DefaultRoles                     []string `json:"DEFAULT_ROLES,omitempty"`
	JwtRoleClaim                     *string  `json:"JWT_ROLE_CLAIM,omitempty"`
	GoogleClientID                   *string  `json:"GOOGLE_CLIENT_ID,omitempty"`
	GoogleClientSecret               *string  `json:"GOOGLE_CLIENT_SECRET,omitempty"`
	GithubClientID                   *string  `json:"GITHUB_CLIENT_ID,omitempty"`
	GithubClientSecret               *string  `json:"GITHUB_CLIENT_SECRET,omitempty"`
	FacebookClientID                 *string  `json:"FACEBOOK_CLIENT_ID,omitempty"`
	FacebookClientSecret             *string  `json:"FACEBOOK_CLIENT_SECRET,omitempty"`
	LinkedinClientID                 *string  `json:"LINKEDIN_CLIENT_ID,omitempty"`
	LinkedinClientSecret             *string  `json:"LINKEDIN_CLIENT_SECRET,omitempty"`
	AppleClientID                    *string  `json:"APPLE_CLIENT_ID,omitempty"`
	AppleClientSecret                *string  `json:"APPLE_CLIENT_SECRET,omitempty"`
	DiscordClientID                  *string  `json:"DISCORD_CLIENT_ID,omitempty"`
	DiscordClientSecret              *string  `json:"DISCORD_CLIENT_SECRET,omitempty"`
	TwitterClientID                  *string  `json:"TWITTER_CLIENT_ID,omitempty"`
	TwitterClientSecret              *string  `json:"TWITTER_CLIENT_SECRET,omitempty"`
	MicrosoftClientID                *string  `json:"MICROSOFT_CLIENT_ID,omitempty"`
	MicrosoftClientSecret            *string  `json:"MICROSOFT_CLIENT_SECRET,omitempty"`
	MicrosoftActiveDirectoryTenantID *string  `json:"MICROSOFT_ACTIVE_DIRECTORY_TENANT_ID,omitempty"`
	TwitchClientID                   *string  `json:"TWITCH_CLIENT_ID,omitempty"`
	TwitchClientSecret               *string  `json:"TWITCH_CLIENT_SECRET,omitempty"`
	RobloxClientID                   *string  `json:"ROBLOX_CLIENT_ID,omitempty"`
	RobloxClientSecret               *string  `json:"ROBLOX_CLIENT_SECRET,omitempty"`
	OrganizationName                 *string  `json:"ORGANIZATION_NAME,omitempty"`
	OrganizationLogo                 *string  `json:"ORGANIZATION_LOGO,omitempty"`
	DefaultAuthorizeResponseType     *string  `json:"DEFAULT_AUTHORIZE_RESPONSE_TYPE,omitempty"`
	DefaultAuthorizeResponseMode     *string  `json:"DEFAULT_AUTHORIZE_RESPONSE_MODE,omitempty"`
	DisablePlayground                *bool    `json:"DISABLE_PLAYGROUND,omitempty"`
	DisableMailOtpLogin              *bool    `json:"DISABLE_MAIL_OTP_LOGIN,omitempty"`
	DisableTotpLogin                 *bool    `json:"DISABLE_TOTP_LOGIN,omitempty"`
}

type UpdateOrgOIDCConnectionRequest struct {
	ID           string  `json:"id"`
	Name         *string `json:"name,omitempty"`
	IssuerURL    *string `json:"issuer_url,omitempty"`
	ClientID     *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	Scopes       *string `json:"scopes,omitempty"`
	RedirectURI  *string `json:"redirect_uri,omitempty"`
	IsActive     *bool   `json:"is_active,omitempty"`
}

type UpdateOrgSAMLConnectionRequest struct {
	ID                string  `json:"id"`
	Name              *string `json:"name,omitempty"`
	IdpEntityID       *string `json:"idp_entity_id,omitempty"`
	IdpSsoURL         *string `json:"idp_sso_url,omitempty"`
	IdpCertificate    *string `json:"idp_certificate,omitempty"`
	SpEntityID        *string `json:"sp_entity_id,omitempty"`
	AcsURL            *string `json:"acs_url,omitempty"`
	AttributeMapping  *string `json:"attribute_mapping,omitempty"`
	AllowIdpInitiated *bool   `json:"allow_idp_initiated,omitempty"`
	IsActive          *bool   `json:"is_active,omitempty"`
}

type UpdateOrganizationRequest struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
}

type UpdateProfileRequest struct {
	OldPassword              *string        `json:"old_password,omitempty"`
	NewPassword              *string        `json:"new_password,omitempty"`
	ConfirmNewPassword       *string        `json:"confirm_new_password,omitempty"`
	Email                    *string        `json:"email,omitempty"`
	GivenName                *string        `json:"given_name,omitempty"`
	FamilyName               *string        `json:"family_name,omitempty"`
	MiddleName               *string        `json:"middle_name,omitempty"`
	Nickname                 *string        `json:"nickname,omitempty"`
	Gender                   *string        `json:"gender,omitempty"`
	Birthdate                *string        `json:"birthdate,omitempty"`
	PhoneNumber              *string        `json:"phone_number,omitempty"`
	Picture                  *string        `json:"picture,omitempty"`
	IsMultiFactorAuthEnabled *bool          `json:"is_multi_factor_auth_enabled,omitempty"`
	AppData                  map[string]any `json:"app_data,omitempty"`
}

type UpdateTrustedIssuerRequest struct {
	ID                       string  `json:"id"`
	Name                     *string `json:"name,omitempty"`
	JwksURL                  *string `json:"jwks_url,omitempty"`
	ExpectedAud              *string `json:"expected_aud,omitempty"`
	AllowedSubjects          *string `json:"allowed_subjects,omitempty"`
	IsActive                 *bool   `json:"is_active,omitempty"`
	SpiffeRefreshHintSeconds *int64  `json:"spiffe_refresh_hint_seconds,omitempty"`
	EnableTokenReview        *bool   `json:"enable_token_review,omitempty"`
	KubernetesAPIServerURL   *string `json:"kubernetes_api_server_url,omitempty"`
}

type UpdateUserRequest struct {
	ID                       string         `json:"id"`
	Email                    *string        `json:"email,omitempty"`
	EmailVerified            *bool          `json:"email_verified,omitempty"`
	GivenName                *string        `json:"given_name,omitempty"`
	FamilyName               *string        `json:"family_name,omitempty"`
	MiddleName               *string        `json:"middle_name,omitempty"`
	Nickname                 *string        `json:"nickname,omitempty"`
	Gender                   *string        `json:"gender,omitempty"`
	Birthdate                *string        `json:"birthdate,omitempty"`
	PhoneNumber              *string        `json:"phone_number,omitempty"`
	PhoneNumberVerified      *bool          `json:"phone_number_verified,omitempty"`
	Picture                  *string        `json:"picture,omitempty"`
	Roles                    []*string      `json:"roles,omitempty"`
	IsMultiFactorAuthEnabled *bool          `json:"is_multi_factor_auth_enabled,omitempty"`
	AppData                  map[string]any `json:"app_data,omitempty"`
}

type UpdateWebhookRequest struct {
	ID               string         `json:"id"`
	EventName        *string        `json:"event_name,omitempty"`
	EventDescription *string        `json:"event_description,omitempty"`
	Endpoint         *string        `json:"endpoint,omitempty"`
	Enabled          *bool          `json:"enabled,omitempty"`
	Headers          map[string]any `json:"headers,omitempty"`
}

type User struct {
	ID                       string         `json:"id"`
	Email                    *string        `json:"email,omitempty"`
	EmailVerified            bool           `json:"email_verified"`
	SignupMethods            string         `json:"signup_methods"`
	GivenName                *string        `json:"given_name,omitempty"`
	FamilyName               *string        `json:"family_name,omitempty"`
	MiddleName               *string        `json:"middle_name,omitempty"`
	Nickname                 *string        `json:"nickname,omitempty"`
	PreferredUsername        *string        `json:"preferred_username,omitempty"`
	Gender                   *string        `json:"gender,omitempty"`
	Birthdate                *string        `json:"birthdate,omitempty"`
	PhoneNumber              *string        `json:"phone_number,omitempty"`
	PhoneNumberVerified      bool           `json:"phone_number_verified"`
	Picture                  *string        `json:"picture,omitempty"`
	Roles                    []string       `json:"roles"`
	CreatedAt                *int64         `json:"created_at,omitempty"`
	UpdatedAt                *int64         `json:"updated_at,omitempty"`
	RevokedTimestamp         *int64         `json:"revoked_timestamp,omitempty"`
	IsMultiFactorAuthEnabled *bool          `json:"is_multi_factor_auth_enabled,omitempty"`
	HasSkippedMfaSetupAt     *int64         `json:"has_skipped_mfa_setup_at,omitempty"`
	AppData                  map[string]any `json:"app_data,omitempty"`
}

type UserOrganization struct {
	Organization *Organization `json:"organization"`
	Roles        []string      `json:"roles"`
}

type UserOrganizations struct {
	Pagination        *Pagination         `json:"pagination"`
	UserOrganizations []*UserOrganization `json:"user_organizations"`
}

type UserOrganizationsRequest struct {
	UserID     string             `json:"user_id"`
	Pagination *PaginationRequest `json:"pagination,omitempty"`
}

type Users struct {
	Pagination *Pagination `json:"pagination"`
	Users      []*User     `json:"users"`
}

type ValidateJWTTokenRequest struct {
	TokenType         string              `json:"token_type"`
	Token             string              `json:"token"`
	Roles             []string            `json:"roles,omitempty"`
	RequiredRelations []*FgaRelationInput `json:"required_relations,omitempty"`
}

type ValidateJWTTokenResponse struct {
	IsValid bool           `json:"is_valid"`
	Claims  map[string]any `json:"claims,omitempty"`
}

type ValidateSessionRequest struct {
	Cookie            string              `json:"cookie"`
	Roles             []string            `json:"roles,omitempty"`
	RequiredRelations []*FgaRelationInput `json:"required_relations,omitempty"`
}

type ValidateSessionResponse struct {
	IsValid bool  `json:"is_valid"`
	User    *User `json:"user"`
}

type VerificationRequest struct {
	ID          string  `json:"id"`
	Identifier  *string `json:"identifier,omitempty"`
	Token       *string `json:"token,omitempty"`
	Email       *string `json:"email,omitempty"`
	Expires     *int64  `json:"expires,omitempty"`
	CreatedAt   *int64  `json:"created_at,omitempty"`
	UpdatedAt   *int64  `json:"updated_at,omitempty"`
	Nonce       *string `json:"nonce,omitempty"`
	RedirectURI *string `json:"redirect_uri,omitempty"`
}

type VerificationRequests struct {
	Pagination           *Pagination            `json:"pagination"`
	VerificationRequests []*VerificationRequest `json:"verification_requests"`
}

type VerifyEmailRequest struct {
	Token string  `json:"token"`
	State *string `json:"state,omitempty"`
}

type VerifyOTPRequest struct {
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	Otp         string  `json:"otp"`
	IsTotp      *bool   `json:"is_totp,omitempty"`
	State       *string `json:"state,omitempty"`
}

type VerifyOrgDomainRequest struct {
	OrgID  string `json:"org_id"`
	Domain string `json:"domain"`
}

type WebauthnCredentialInfo struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Transports []string `json:"transports,omitempty"`
	CreatedAt  *int64   `json:"created_at,omitempty"`
	UpdatedAt  *int64   `json:"updated_at,omitempty"`
	LastUsedAt *int64   `json:"last_used_at,omitempty"`
}

type WebauthnLoginOptionsResponse struct {
	Options string `json:"options"`
}

type WebauthnLoginVerifyRequest struct {
	State      *string `json:"state,omitempty"`
	Credential string  `json:"credential"`
}

type WebauthnRegistrationOptionsResponse struct {
	Options string `json:"options"`
}

type WebauthnRegistrationVerifyRequest struct {
	Name       *string `json:"name,omitempty"`
	Credential string  `json:"credential"`
}

type Webhook struct {
	ID               string         `json:"id"`
	EventName        *string        `json:"event_name,omitempty"`
	EventDescription *string        `json:"event_description,omitempty"`
	Endpoint         *string        `json:"endpoint,omitempty"`
	Enabled          *bool          `json:"enabled,omitempty"`
	Headers          map[string]any `json:"headers,omitempty"`
	CreatedAt        *int64         `json:"created_at,omitempty"`
	UpdatedAt        *int64         `json:"updated_at,omitempty"`
}

type WebhookLog struct {
	ID         string  `json:"id"`
	HTTPStatus *int64  `json:"http_status,omitempty"`
	Response   *string `json:"response,omitempty"`
	Request    *string `json:"request,omitempty"`
	WebhookID  *string `json:"webhook_id,omitempty"`
	CreatedAt  *int64  `json:"created_at,omitempty"`
	UpdatedAt  *int64  `json:"updated_at,omitempty"`
}

type WebhookLogs struct {
	Pagination  *Pagination   `json:"pagination"`
	WebhookLogs []*WebhookLog `json:"webhook_logs"`
}

type WebhookRequest struct {
	ID string `json:"id"`
}

type Webhooks struct {
	Pagination *Pagination `json:"pagination"`
	Webhooks   []*Webhook  `json:"webhooks"`
}
