// e2e-playground/tests/social/twitter.spec.ts
import { test, expect } from '@playwright/test';
import crypto from 'node:crypto';
import { runSocialLoginHappyPath, runConsentDeniedNegativePath } from './helpers';
import { getUserByNickname } from '../../fixtures/adminClient';

test.describe('Social login — Twitter/X', () => {
  test('first-time signup via Twitter (PKCE flow) creates an account with mapped profile fields', async ({
    page,
    request,
  }) => {
    // Twitter/X uses PKCE (internal/http_handlers/oauth_callback.go's
    // processTwitterUserInfo calls cfg.Exchange with oauth2.VerifierOption;
    // the verifier is generated by /oauth_login/twitter and stashed
    // server-side, keyed by state, then retrieved at callback time). That
    // exchange is entirely server-to-server - mock-oauth's /token endpoint
    // issues tokens unconditionally without checking the code_verifier - so
    // driving the browser through the button click and redirect chain below
    // exercises the real PKCE round trip with no special handling needed
    // here; a broken verifier lookup would surface as the login simply
    // failing to establish a session.
    const nickname = `ada-${crypto.randomUUID()}`;
    // Twitter's REST profile is nested under `data` (real API v2 shape) and
    // only has a single `name` field - no given/family name split like
    // Twitch/Google. mock-oauth's /twitter/userinfo route (server.ts)
    // returns this back verbatim.
    await runSocialLoginHappyPath(page, request, {
      provider: 'twitter',
      buttonName: /twitter|x\.com/i,
      profile: {
        data: { id: 'twitter-1', name: 'Ada Lovelace', username: nickname, profile_image_url: 'https://example.com/a.png' },
      },
      // No expectedEmail: real Twitter never returns an email address (not a
      // mock gap - processTwitterUserInfo has no email extraction at all),
      // so there is nothing to assert a mailto link against. The dashboard's
      // "Signed in as" text is still the same real proof of an established
      // session every other provider spec relies on.
    });

    // processTwitterUserInfo splits `name` with strings.SplitAfterN(name, " ", 2),
    // which - unlike SplitN - keeps the separator on the first piece: for
    // "Ada Lovelace" that's given_name "Ada " (trailing space included) and
    // family_name "Lovelace", not the clean "Ada"/"Lovelace" split GitHub's
    // SplitN-based logic produces. Asserting the literal trailing space
    // proves this is exercising the real Twitter-specific split, not a
    // copy-pasted GitHub-style assertion.
    const user = await getUserByNickname(nickname);
    expect(user.given_name).toBe('Ada ');
    expect(user.family_name).toBe('Lovelace');
    expect(user.nickname).toBe(nickname);
    expect(user.signup_methods).toContain('twitter');
  });

  test('consent denied at provider is rejected without a session, and the state cannot be replayed', async ({
    request,
    baseURL,
  }) => {
    await runConsentDeniedNegativePath(request, baseURL!, 'twitter');
  });
});
