package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/authorizerdev/authorizer/internal/graph/generated"
	"github.com/authorizerdev/authorizer/internal/graph/model"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, params model.SignUpRequest) (*model.AuthResponse, error) {
	return r.GraphQLProvider.SignUp(ctx, &params)
}

// MobileSignup is the resolver for the mobile_signup field.
func (r *mutationResolver) MobileSignup(ctx context.Context, params *model.MobileSignUpRequest) (*model.AuthResponse, error) {
	return nil, fmt.Errorf("deprecated, use signup with mobile phone_number")
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, params model.LoginRequest) (*model.AuthResponse, error) {
	return r.GraphQLProvider.Login(ctx, &params)
}

// MobileLogin is the resolver for the mobile_login field.
func (r *mutationResolver) MobileLogin(ctx context.Context, params model.MobileLoginRequest) (*model.AuthResponse, error) {
	return nil, fmt.Errorf("deprecated, use login with mobile phone_number")
}

// MagicLinkLogin is the resolver for the magic_link_login field.
func (r *mutationResolver) MagicLinkLogin(ctx context.Context, params model.MagicLinkLoginRequest) (*model.Response, error) {
	return r.GraphQLProvider.MagicLinkLogin(ctx, &params)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.Response, error) {
	return r.GraphQLProvider.Logout(ctx)
}

// UpdateProfile is the resolver for the update_profile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, params model.UpdateProfileRequest) (*model.Response, error) {
	return r.GraphQLProvider.UpdateProfile(ctx, &params)
}

// VerifyEmail is the resolver for the verify_email field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, params model.VerifyEmailRequest) (*model.AuthResponse, error) {
	return r.GraphQLProvider.VerifyEmail(ctx, &params)
}

// ResendVerifyEmail is the resolver for the resend_verify_email field.
func (r *mutationResolver) ResendVerifyEmail(ctx context.Context, params model.ResendVerifyEmailRequest) (*model.Response, error) {
	return r.GraphQLProvider.ResendVerifyEmail(ctx, &params)
}

// ForgotPassword is the resolver for the forgot_password field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, params model.ForgotPasswordRequest) (*model.ForgotPasswordResponse, error) {
	return r.GraphQLProvider.ForgotPassword(ctx, &params)
}

// ResetPassword is the resolver for the reset_password field.
func (r *mutationResolver) ResetPassword(ctx context.Context, params model.ResetPasswordRequest) (*model.Response, error) {
	return r.GraphQLProvider.ResetPassword(ctx, &params)
}

// Revoke is the resolver for the revoke field.
func (r *mutationResolver) Revoke(ctx context.Context, params model.OAuthRevokeRequest) (*model.Response, error) {
	return r.GraphQLProvider.Revoke(ctx, &params)
}

// VerifyOtp is the resolver for the verify_otp field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, params model.VerifyOTPRequest) (*model.AuthResponse, error) {
	return r.GraphQLProvider.VerifyOTP(ctx, &params)
}

// ResendOtp is the resolver for the resend_otp field.
func (r *mutationResolver) ResendOtp(ctx context.Context, params model.ResendOTPRequest) (*model.Response, error) {
	return r.GraphQLProvider.ResendOTP(ctx, &params)
}

// WebauthnRegistrationOptions is the resolver for the webauthn_registration_options field.
func (r *mutationResolver) WebauthnRegistrationOptions(ctx context.Context, email *string) (*model.WebauthnRegistrationOptionsResponse, error) {
	return r.GraphQLProvider.WebauthnRegistrationOptions(ctx, email)
}

// WebauthnRegistrationVerify is the resolver for the webauthn_registration_verify field.
func (r *mutationResolver) WebauthnRegistrationVerify(ctx context.Context, params model.WebauthnRegistrationVerifyRequest) (*model.Response, error) {
	return r.GraphQLProvider.WebauthnRegistrationVerify(ctx, &params)
}

// WebauthnLoginOptions is the resolver for the webauthn_login_options field.
func (r *mutationResolver) WebauthnLoginOptions(ctx context.Context, email *string) (*model.WebauthnLoginOptionsResponse, error) {
	return r.GraphQLProvider.WebauthnLoginOptions(ctx, email)
}

// WebauthnLoginVerify is the resolver for the webauthn_login_verify field.
func (r *mutationResolver) WebauthnLoginVerify(ctx context.Context, params model.WebauthnLoginVerifyRequest) (*model.AuthResponse, error) {
	return r.GraphQLProvider.WebauthnLoginVerify(ctx, &params)
}

// WebauthnDeleteCredential is the resolver for the webauthn_delete_credential field.
func (r *mutationResolver) WebauthnDeleteCredential(ctx context.Context, id string) (*model.Response, error) {
	return r.GraphQLProvider.WebauthnDeleteCredential(ctx, id)
}

// DeactivateAccount is the resolver for the deactivate_account field.
func (r *mutationResolver) DeactivateAccount(ctx context.Context) (*model.Response, error) {
	return r.GraphQLProvider.DeactivateAccount(ctx)
}

// DeleteUser is the resolver for the _delete_user field.
func (r *mutationResolver) DeleteUser(ctx context.Context, params model.DeleteUserRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteUser(ctx, &params)
}

// UpdateUser is the resolver for the _update_user field.
func (r *mutationResolver) UpdateUser(ctx context.Context, params model.UpdateUserRequest) (*model.User, error) {
	return r.GraphQLProvider.UpdateUser(ctx, &params)
}

// AdminSignup is the resolver for the _admin_signup field.
func (r *mutationResolver) AdminSignup(ctx context.Context, params model.AdminSignupRequest) (*model.Response, error) {
	return nil, fmt.Errorf("deprecated. please configure admin secret via cli args")
}

// AdminLogin is the resolver for the _admin_login field.
func (r *mutationResolver) AdminLogin(ctx context.Context, params model.AdminLoginRequest) (*model.Response, error) {
	return r.GraphQLProvider.AdminLogin(ctx, &params)
}

// AdminLogout is the resolver for the _admin_logout field.
func (r *mutationResolver) AdminLogout(ctx context.Context) (*model.Response, error) {
	return r.GraphQLProvider.AdminLogout(ctx)
}

// UpdateEnv is the resolver for the _update_env field.
func (r *mutationResolver) UpdateEnv(ctx context.Context, params model.UpdateEnvRequest) (*model.Response, error) {
	return nil, fmt.Errorf("deprecated. please configure env via cli args")
}

// InviteMembers is the resolver for the _invite_members field.
func (r *mutationResolver) InviteMembers(ctx context.Context, params model.InviteMemberRequest) (*model.InviteMembersResponse, error) {
	return r.GraphQLProvider.InviteMembers(ctx, &params)
}

// RevokeAccess is the resolver for the _revoke_access field.
func (r *mutationResolver) RevokeAccess(ctx context.Context, param model.UpdateAccessRequest) (*model.Response, error) {
	return r.GraphQLProvider.RevokeAccess(ctx, &param)
}

// EnableAccess is the resolver for the _enable_access field.
func (r *mutationResolver) EnableAccess(ctx context.Context, param model.UpdateAccessRequest) (*model.Response, error) {
	return r.GraphQLProvider.EnableAccess(ctx, &param)
}

// GenerateJwtKeys is the resolver for the _generate_jwt_keys field.
func (r *mutationResolver) GenerateJwtKeys(ctx context.Context, params model.GenerateJWTKeysRequest) (*model.GenerateJWTKeysResponse, error) {
	return nil, fmt.Errorf("deprecated. please configure jwt keys via cli args")
}

// AddWebhook is the resolver for the _add_webhook field.
func (r *mutationResolver) AddWebhook(ctx context.Context, params model.AddWebhookRequest) (*model.Response, error) {
	return r.GraphQLProvider.AddWebhook(ctx, &params)
}

// UpdateWebhook is the resolver for the _update_webhook field.
func (r *mutationResolver) UpdateWebhook(ctx context.Context, params model.UpdateWebhookRequest) (*model.Response, error) {
	return r.GraphQLProvider.UpdateWebhook(ctx, &params)
}

// DeleteWebhook is the resolver for the _delete_webhook field.
func (r *mutationResolver) DeleteWebhook(ctx context.Context, params model.WebhookRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteWebhook(ctx, &params)
}

// CreateClient is the resolver for the _create_service_account field.
func (r *mutationResolver) CreateClient(ctx context.Context, params model.CreateClientRequest) (*model.CreateClientResponse, error) {
	return r.GraphQLProvider.CreateClient(ctx, &params)
}

// UpdateClient is the resolver for the _update_service_account field.
func (r *mutationResolver) UpdateClient(ctx context.Context, params model.UpdateClientRequest) (*model.Client, error) {
	return r.GraphQLProvider.UpdateClient(ctx, &params)
}

// DeleteClient is the resolver for the _delete_service_account field.
func (r *mutationResolver) DeleteClient(ctx context.Context, params model.ClientRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteClient(ctx, &params)
}

// RotateClientSecret is the resolver for the _rotate_service_account_secret field.
func (r *mutationResolver) RotateClientSecret(ctx context.Context, params model.ClientRequest) (*model.CreateClientResponse, error) {
	return r.GraphQLProvider.RotateClientSecret(ctx, &params)
}

// AddTrustedIssuer is the resolver for the _add_trusted_issuer field.
func (r *mutationResolver) AddTrustedIssuer(ctx context.Context, params model.AddTrustedIssuerRequest) (*model.TrustedIssuer, error) {
	return r.GraphQLProvider.AddTrustedIssuer(ctx, &params)
}

// UpdateTrustedIssuer is the resolver for the _update_trusted_issuer field.
func (r *mutationResolver) UpdateTrustedIssuer(ctx context.Context, params model.UpdateTrustedIssuerRequest) (*model.TrustedIssuer, error) {
	return r.GraphQLProvider.UpdateTrustedIssuer(ctx, &params)
}

// DeleteTrustedIssuer is the resolver for the _delete_trusted_issuer field.
func (r *mutationResolver) DeleteTrustedIssuer(ctx context.Context, params model.TrustedIssuerRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteTrustedIssuer(ctx, &params)
}

// CreateOrgOidcConnection is the resolver for the _create_org_oidc_connection field.
func (r *mutationResolver) CreateOrgOidcConnection(ctx context.Context, params model.CreateOrgOIDCConnectionRequest) (*model.OrgOIDCConnection, error) {
	return r.GraphQLProvider.CreateOrgOidcConnection(ctx, &params)
}

// UpdateOrgOidcConnection is the resolver for the _update_org_oidc_connection field.
func (r *mutationResolver) UpdateOrgOidcConnection(ctx context.Context, params model.UpdateOrgOIDCConnectionRequest) (*model.OrgOIDCConnection, error) {
	return r.GraphQLProvider.UpdateOrgOidcConnection(ctx, &params)
}

// DeleteOrgOidcConnection is the resolver for the _delete_org_oidc_connection field.
func (r *mutationResolver) DeleteOrgOidcConnection(ctx context.Context, params model.OrgOIDCConnectionRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteOrgOidcConnection(ctx, &params)
}

// CreateOrgSamlConnection is the resolver for the _create_org_saml_connection field.
func (r *mutationResolver) CreateOrgSamlConnection(ctx context.Context, params model.CreateOrgSAMLConnectionRequest) (*model.OrgSAMLConnection, error) {
	return r.GraphQLProvider.CreateOrgSamlConnection(ctx, &params)
}

// UpdateOrgSamlConnection is the resolver for the _update_org_saml_connection field.
func (r *mutationResolver) UpdateOrgSamlConnection(ctx context.Context, params model.UpdateOrgSAMLConnectionRequest) (*model.OrgSAMLConnection, error) {
	return r.GraphQLProvider.UpdateOrgSamlConnection(ctx, &params)
}

// DeleteOrgSamlConnection is the resolver for the _delete_org_saml_connection field.
func (r *mutationResolver) DeleteOrgSamlConnection(ctx context.Context, params model.OrgSAMLConnectionRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteOrgSamlConnection(ctx, &params)
}

// CreateOrganization is the resolver for the _create_organization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, params model.CreateOrganizationRequest) (*model.Organization, error) {
	return r.GraphQLProvider.CreateOrganization(ctx, &params)
}

// UpdateOrganization is the resolver for the _update_organization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, params model.UpdateOrganizationRequest) (*model.Organization, error) {
	return r.GraphQLProvider.UpdateOrganization(ctx, &params)
}

// DeleteOrganization is the resolver for the _delete_organization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, params model.OrganizationRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteOrganization(ctx, &params)
}

// AddOrgMember is the resolver for the _add_org_member field.
func (r *mutationResolver) AddOrgMember(ctx context.Context, params model.AddOrgMemberRequest) (*model.OrgMember, error) {
	return r.GraphQLProvider.AddOrgMember(ctx, &params)
}

// RemoveOrgMember is the resolver for the _remove_org_member field.
func (r *mutationResolver) RemoveOrgMember(ctx context.Context, params model.RemoveOrgMemberRequest) (*model.Response, error) {
	return r.GraphQLProvider.RemoveOrgMember(ctx, &params)
}

// CreateScimEndpoint is the resolver for the _create_scim_endpoint field.
func (r *mutationResolver) CreateScimEndpoint(ctx context.Context, params model.CreateScimEndpointRequest) (*model.CreateScimEndpointResponse, error) {
	return r.GraphQLProvider.CreateScimEndpoint(ctx, &params)
}

// RotateScimToken is the resolver for the _rotate_scim_token field.
func (r *mutationResolver) RotateScimToken(ctx context.Context, params model.ScimEndpointRequest) (*model.CreateScimEndpointResponse, error) {
	return r.GraphQLProvider.RotateScimToken(ctx, &params)
}

// DeleteScimEndpoint is the resolver for the _delete_scim_endpoint field.
func (r *mutationResolver) DeleteScimEndpoint(ctx context.Context, params model.ScimEndpointRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteScimEndpoint(ctx, &params)
}

// RequestOrgDomain is the resolver for the _request_org_domain field.
func (r *mutationResolver) RequestOrgDomain(ctx context.Context, params model.RequestOrgDomainRequest) (*model.OrgDomainChallenge, error) {
	return r.GraphQLProvider.RequestOrgDomain(ctx, &params)
}

// VerifyOrgDomain is the resolver for the _verify_org_domain field.
func (r *mutationResolver) VerifyOrgDomain(ctx context.Context, params model.VerifyOrgDomainRequest) (*model.OrgDomain, error) {
	return r.GraphQLProvider.VerifyOrgDomain(ctx, &params)
}

// AddVerifiedOrgDomain is the resolver for the _add_verified_org_domain field.
func (r *mutationResolver) AddVerifiedOrgDomain(ctx context.Context, params model.AddVerifiedOrgDomainRequest) (*model.OrgDomain, error) {
	return r.GraphQLProvider.AddVerifiedOrgDomain(ctx, &params)
}

// DeleteOrgDomain is the resolver for the _delete_org_domain field.
func (r *mutationResolver) DeleteOrgDomain(ctx context.Context, params model.DeleteOrgDomainRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteOrgDomain(ctx, &params)
}

// TestEndpoint is the resolver for the _test_endpoint field.
func (r *mutationResolver) TestEndpoint(ctx context.Context, params model.TestEndpointRequest) (*model.TestEndpointResponse, error) {
	return r.GraphQLProvider.TestEndpoint(ctx, &params)
}

// AddEmailTemplate is the resolver for the _add_email_template field.
func (r *mutationResolver) AddEmailTemplate(ctx context.Context, params model.AddEmailTemplateRequest) (*model.Response, error) {
	return r.GraphQLProvider.AddEmailTemplate(ctx, &params)
}

// UpdateEmailTemplate is the resolver for the _update_email_template field.
func (r *mutationResolver) UpdateEmailTemplate(ctx context.Context, params model.UpdateEmailTemplateRequest) (*model.Response, error) {
	return r.GraphQLProvider.UpdateEmailTemplate(ctx, &params)
}

// DeleteEmailTemplate is the resolver for the _delete_email_template field.
func (r *mutationResolver) DeleteEmailTemplate(ctx context.Context, params model.DeleteEmailTemplateRequest) (*model.Response, error) {
	return r.GraphQLProvider.DeleteEmailTemplate(ctx, &params)
}

// FgaWriteModel is the resolver for the _fga_write_model field.
func (r *mutationResolver) FgaWriteModel(ctx context.Context, params model.FgaWriteModelInput) (*model.FgaModel, error) {
	return r.GraphQLProvider.FgaWriteModel(ctx, &params)
}

// FgaWriteTuples is the resolver for the _fga_write_tuples field.
func (r *mutationResolver) FgaWriteTuples(ctx context.Context, params model.FgaWriteTuplesInput) (*model.Response, error) {
	return r.GraphQLProvider.FgaWriteTuples(ctx, &params)
}

// FgaDeleteTuples is the resolver for the _fga_delete_tuples field.
func (r *mutationResolver) FgaDeleteTuples(ctx context.Context, params model.FgaWriteTuplesInput) (*model.Response, error) {
	return r.GraphQLProvider.FgaDeleteTuples(ctx, &params)
}

// FgaReset is the resolver for the _fga_reset field.
func (r *mutationResolver) FgaReset(ctx context.Context) (*model.Response, error) {
	return r.GraphQLProvider.FgaReset(ctx)
}

// Meta is the resolver for the meta field.
func (r *queryResolver) Meta(ctx context.Context) (*model.Meta, error) {
	return r.GraphQLProvider.Meta(ctx)
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, params *model.SessionQueryRequest) (*model.AuthResponse, error) {
	return r.GraphQLProvider.Session(ctx, params)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.User, error) {
	return r.GraphQLProvider.Profile(ctx)
}

// ValidateJwtToken is the resolver for the validate_jwt_token field.
func (r *queryResolver) ValidateJwtToken(ctx context.Context, params model.ValidateJWTTokenRequest) (*model.ValidateJWTTokenResponse, error) {
	return r.GraphQLProvider.ValidateJWTToken(ctx, &params)
}

// ValidateSession is the resolver for the validate_session field.
func (r *queryResolver) ValidateSession(ctx context.Context, params *model.ValidateSessionRequest) (*model.ValidateSessionResponse, error) {
	return r.GraphQLProvider.ValidateSession(ctx, params)
}

// WebauthnCredentials is the resolver for the webauthn_credentials field.
func (r *queryResolver) WebauthnCredentials(ctx context.Context) ([]*model.WebauthnCredentialInfo, error) {
	return r.GraphQLProvider.WebauthnCredentials(ctx)
}

// Users is the resolver for the _users field.
func (r *queryResolver) Users(ctx context.Context, params *model.ListUsersRequest) (*model.Users, error) {
	return r.GraphQLProvider.Users(ctx, params)
}

// User is the resolver for the _user field.
func (r *queryResolver) User(ctx context.Context, params model.GetUserRequest) (*model.User, error) {
	return r.GraphQLProvider.User(ctx, &params)
}

// UserOrganizations is the resolver for the _user_organizations field.
func (r *queryResolver) UserOrganizations(ctx context.Context, params model.UserOrganizationsRequest) (*model.UserOrganizations, error) {
	return r.GraphQLProvider.UserOrganizations(ctx, &params)
}

// VerificationRequests is the resolver for the _verification_requests field.
func (r *queryResolver) VerificationRequests(ctx context.Context, params *model.PaginatedRequest) (*model.VerificationRequests, error) {
	return r.GraphQLProvider.VerificationRequests(ctx, params)
}

// AdminSession is the resolver for the _admin_session field.
func (r *queryResolver) AdminSession(ctx context.Context) (*model.Response, error) {
	return r.GraphQLProvider.AdminSession(ctx)
}

// AdminMeta is the resolver for the _admin_meta field.
func (r *queryResolver) AdminMeta(ctx context.Context) (*model.AdminMeta, error) {
	return r.GraphQLProvider.AdminMeta(ctx)
}

// Env is the resolver for the _env field.
func (r *queryResolver) Env(ctx context.Context) (*model.Env, error) {
	return nil, fmt.Errorf("deprecated. please configure env via cli args")
}

// Webhook is the resolver for the _webhook field.
func (r *queryResolver) Webhook(ctx context.Context, params model.WebhookRequest) (*model.Webhook, error) {
	return r.GraphQLProvider.Webhook(ctx, &params)
}

// Webhooks is the resolver for the _webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context, params *model.PaginatedRequest) (*model.Webhooks, error) {
	return r.GraphQLProvider.Webhooks(ctx, params)
}

// WebhookLogs is the resolver for the _webhook_logs field.
func (r *queryResolver) WebhookLogs(ctx context.Context, params *model.ListWebhookLogRequest) (*model.WebhookLogs, error) {
	return r.GraphQLProvider.WebhookLogs(ctx, params)
}

// Client is the resolver for the _service_account field.
func (r *queryResolver) Client(ctx context.Context, params model.ClientRequest) (*model.Client, error) {
	return r.GraphQLProvider.Client(ctx, &params)
}

// Clients is the resolver for the _service_accounts field.
func (r *queryResolver) Clients(ctx context.Context, params *model.ListClientsRequest) (*model.Clients, error) {
	return r.GraphQLProvider.Clients(ctx, params)
}

// TrustedIssuer is the resolver for the _trusted_issuer field.
func (r *queryResolver) TrustedIssuer(ctx context.Context, params model.TrustedIssuerRequest) (*model.TrustedIssuer, error) {
	return r.GraphQLProvider.TrustedIssuer(ctx, &params)
}

// TrustedIssuers is the resolver for the _trusted_issuers field.
func (r *queryResolver) TrustedIssuers(ctx context.Context, params *model.ListTrustedIssuersRequest) (*model.TrustedIssuers, error) {
	return r.GraphQLProvider.TrustedIssuers(ctx, params)
}

// OrgOidcConnection is the resolver for the _org_oidc_connection field.
func (r *queryResolver) OrgOidcConnection(ctx context.Context, params model.OrgOIDCConnectionRequest) (*model.OrgOIDCConnection, error) {
	return r.GraphQLProvider.OrgOidcConnection(ctx, &params)
}

// OrgSamlConnection is the resolver for the _org_saml_connection field.
func (r *queryResolver) OrgSamlConnection(ctx context.Context, params model.OrgSAMLConnectionRequest) (*model.OrgSAMLConnection, error) {
	return r.GraphQLProvider.OrgSamlConnection(ctx, &params)
}

// Organization is the resolver for the _organization field.
func (r *queryResolver) Organization(ctx context.Context, params model.OrganizationRequest) (*model.Organization, error) {
	return r.GraphQLProvider.Organization(ctx, &params)
}

// Organizations is the resolver for the _organizations field.
func (r *queryResolver) Organizations(ctx context.Context, params *model.ListOrganizationsRequest) (*model.Organizations, error) {
	return r.GraphQLProvider.Organizations(ctx, params)
}

// OrgMembers is the resolver for the _org_members field.
func (r *queryResolver) OrgMembers(ctx context.Context, params model.ListOrgMembersRequest) (*model.OrgMembers, error) {
	return r.GraphQLProvider.OrgMembers(ctx, &params)
}

// ScimEndpoint is the resolver for the _scim_endpoint field.
func (r *queryResolver) ScimEndpoint(ctx context.Context, params model.ScimEndpointRequest) (*model.ScimEndpoint, error) {
	return r.GraphQLProvider.ScimEndpoint(ctx, &params)
}

// OrgDomains is the resolver for the _org_domains field.
func (r *queryResolver) OrgDomains(ctx context.Context, params model.ListOrgDomainsRequest) (*model.OrgDomains, error) {
	return r.GraphQLProvider.OrgDomains(ctx, &params)
}

// EmailTemplates is the resolver for the _email_templates field.
func (r *queryResolver) EmailTemplates(ctx context.Context, params *model.PaginatedRequest) (*model.EmailTemplates, error) {
	return r.GraphQLProvider.EmailTemplates(ctx, params)
}

// AuditLogs is the resolver for the _audit_logs field.
func (r *queryResolver) AuditLogs(ctx context.Context, params *model.ListAuditLogRequest) (*model.AuditLogs, error) {
	return r.GraphQLProvider.AuditLogs(ctx, params)
}

// FgaGetModel is the resolver for the _fga_get_model field.
func (r *queryResolver) FgaGetModel(ctx context.Context) (*model.FgaModel, error) {
	return r.GraphQLProvider.FgaGetModel(ctx)
}

// FgaReadTuples is the resolver for the _fga_read_tuples field.
func (r *queryResolver) FgaReadTuples(ctx context.Context, params model.FgaReadTuplesInput) (*model.FgaTuples, error) {
	return r.GraphQLProvider.FgaReadTuples(ctx, &params)
}

// FgaListUsers is the resolver for the _fga_list_users field.
func (r *queryResolver) FgaListUsers(ctx context.Context, params model.FgaListUsersInput) (*model.FgaListUsersResponse, error) {
	return r.GraphQLProvider.FgaListUsers(ctx, &params)
}

// FgaExpand is the resolver for the _fga_expand field.
func (r *queryResolver) FgaExpand(ctx context.Context, params model.FgaExpandInput) (*model.FgaExpandResponse, error) {
	return r.GraphQLProvider.FgaExpand(ctx, &params)
}

// CheckPermissions is the resolver for the check_permissions field.
func (r *queryResolver) CheckPermissions(ctx context.Context, params model.CheckPermissionsInput) (*model.CheckPermissionsResponse, error) {
	return r.GraphQLProvider.CheckPermissions(ctx, &params)
}

// ListPermissions is the resolver for the list_permissions field.
func (r *queryResolver) ListPermissions(ctx context.Context, params model.ListPermissionsInput) (*model.ListPermissionsResponse, error) {
	return r.GraphQLProvider.ListPermissions(ctx, &params)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
